# Docs: https://docs.docker.com/compose/compose-file/ 
# Version of docker-compose
version: "3.8"
# Services/Container that will be built
services:
    # Service Name
    nginx:
        build:
            # Path to a directory that will be used
            # as context to find the dockerfile
            context: .
            # Dockerfile path from the "vision" of
            # the previous defined context
            dockerfile: .docker/nginx/Dockerfile
        # Image name/ID
        image: go-proj-nginx
        # Custom name for the container
        container_name: go-proj-nginx
        # Expose ports
        # HOST:CONTAINER
        ports:
            - "${APP_PORT}:80"
        # This will define the Services that this service
        # depends on, so they will be mounted/built before
        depends_on:
            - "app"
    app:
        build:
            context: .
            dockerfile: .docker/go/Dockerfile
        image: go-proj-app 
        container_name: go-proj-app
        restart: always
        ports:
            - "8080"
        volumes:
            - ./:/var/www/html
        depends_on:
            - "postgres"
            - "postgres-test"
    postgres:
        build:
            context: .
            dockerfile: .docker/postgresql/Dockerfile
        ports:
            - "${POSTGRES_PORT}:5432"
        image: go-proj-postgres
        container_name: go-proj-postgres
        environment:
            - PGDATA=${POSTGRES_DATA}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    postgres-test:
        build:
            context: .
            dockerfile: .docker/postgresql/Dockerfile
        ports:
            - "${POSTGRES_TEST_PORT}:5432"
        image: go-proj-postgres-test
        container_name: go-proj-postgres-test
        environment:
            - PGDATA=${POSTGRES_TEST_DATA}
            - POSTGRES_DB=${POSTGRES_TEST_DB}
            - POSTGRES_USER=${POSTGRES_TEST_USER}
            - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
